import{a as v,S as q,i as d}from"./assets/vendor-DqB7j7Ix.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const E="https://pixabay.com/api/",M="50786624-1add8080b253d44feed6410de";async function f(e,o){try{return(await v.get(E,{params:{key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15}})).data}catch{iziToast.error({title:"Error",message:"Something went wrong. Try again later.",position:"center"})}}const y=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".button-more"),P=new q(".gallery a",{captionPosition:"bottom",captionDelay:250,overlayOpacity:.3});function p(e){const o=e.map(({webformatURL:n,largeImageURL:s,tags:t,likes:r,views:a,comments:w,downloads:S})=>`
      <li class="gallery-item">
        <a href="${s}">
          <img src="${n}" alt="${t}" />
        </a>
        <div class="gallery-info">
          <p><b>Likes</b> ${r}</p>
          <p><b>Views</b> ${a}</p>
          <p><b>Comments</b> ${w}</p>
          <p><b>Downloads</b> ${S}</p>
        </div>
      </li>`).join("");y.insertAdjacentHTML("beforeend",o),P.refresh()}function $(){y.innerHTML=""}function g(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}function B(){m.classList.remove("hidden")}function c(){m.classList.add("hidden")}const O=document.querySelector(".form"),T=document.querySelector('input[name="search-text"]'),x=document.querySelector(".button-more");let i=1,l="";O.addEventListener("submit",A);async function A(e){e.preventDefault();const o=T.value.trim();if(!o){u("Please enter a search query.");return}l=o,i=1,$(),c(),g();try{const n=await f(l,i);if(n.hits.length===0){R("Sorry, no images match your query.");return}p(n.hits),i*15>=n.totalHits?(c(),L("We're sorry, but you've reached the end of search results.")):B()}catch{u("Something went wrong. Try again later.")}finally{b()}}x.addEventListener("click",H);async function H(){i+=1,g();try{const e=await f(l,i);p(e.hits),I(),i*15>=e.totalHits&&(c(),L("We're sorry, but you've reached the end of search results."))}catch{u("Something went wrong. Try again later.")}finally{b()}}function I(){const e=document.querySelector(".gallery-item");if(!e)return;const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}const u=e=>d.error({title:"Error",message:e,position:"topRight"}),R=e=>d.warning({title:"Warning",message:e,position:"center"}),L=e=>d.info({title:"Info",message:e,position:"topRight"});
//# sourceMappingURL=index.js.map
